export const CANDIDATE_FORM_TEST_DATA = {
  firstName: 'John',
  lastName: 'Doe',
  email: 'john.doe@example.com',
  dateOfBirth: '1990-06-15T00:00:00.000Z',
  shirtSize: 'L',
  maritalStatus: 'married' as const,
  hasSpouseAttendedWeekend: true,
  spouseWeekendLocation: 'Dusty Trails Tres Dias',
  spouseName: 'Jane Doe',
  hasFriendsAttendingWeekend: false,
  isChristian: true,
  church: 'First Baptist Church',
  memberOfClergy: false,
  reasonForAttending:
    'I want to deepen my relationship with God and grow in my faith.',
  addressLine1: '123 Main Street',
  addressLine2: 'Apt 4B',
  city: 'Dallas',
  state: 'TX',
  zip: '75201',
  phone: '5551234567',
  emergencyContactName: 'Jane Doe',
  emergencyContactPhone: '5559876543',
  medicalConditions: 'None',
  medicalPermission: true,
  emergencyContactPermission: true,
}
