# https://taskfile.dev

version: '3'

vars:
  NODE_VERSION_REQUIRED: "22"
  NODE_VERSION_EXACT: "22.21.1"
  INFISICAL_PATH: "/Development"

tasks:
  setup:
    desc: Set up local development environment
    silent: true
    cmds:
      - task: check-prereqs
      - echo ""
      - echo "✓ All prerequisites satisfied"
      - echo ""
      - echo "Proceeding with environment setup..."
      - task: install-deps
      - task: pull-secrets
      - task: write-supabase-keys
      - echo ""
      - echo "🎉 Setup complete! Run 'yarn dev' to start the development server."

  install-deps:
    desc: Install project dependencies
    internal: true
    silent: true
    cmds:
      - |
        echo "Installing project dependencies..."
        yarn install
        if [ $? -ne 0 ]; then
          echo "Failed to install dependencies."
          exit 1
        fi
        echo "✓ Dependencies installed"

  check-prereqs:
    desc: Check that all required development prerequisites are installed
    silent: true
    cmds:
      - task: check-node
      - task: check-yarn
      - task: check-docker
      - task: check-infisical
      - task: check-stripe

  check-node:
    desc: Check Node.js is installed and meets version requirements
    internal: true
    silent: true
    cmds:
      - |
        if ! command -v node > /dev/null 2>&1; then
          printf "Node.js is required; install? [Y/n] "
          read response
          response=${response:-Y}
          case "$response" in
            [Yy]*)
              echo "Installing Node.js via nvm..."
              if command -v nvm > /dev/null 2>&1; then
                nvm install {{.NODE_VERSION_EXACT}}
                nvm use {{.NODE_VERSION_EXACT}}
              else
                echo "Please install Node.js v{{.NODE_VERSION_EXACT}} manually:"
                echo "  - Install nvm: https://github.com/nvm-sh/nvm"
                echo "  - Then run: nvm install {{.NODE_VERSION_EXACT}}"
                exit 1
              fi
              ;;
            *)
              echo "Node.js is required to continue. Exiting."
              exit 1
              ;;
          esac
        fi

        NODE_VERSION=$(node -v | sed 's/v//' | cut -d. -f1)
        if [ "$NODE_VERSION" -lt "{{.NODE_VERSION_REQUIRED}}" ]; then
          echo "Node.js v{{.NODE_VERSION_REQUIRED}}+ is required. Current version: $(node -v)"
          echo "Please upgrade Node.js to v{{.NODE_VERSION_EXACT}} (see .nvmrc)"
          exit 1
        fi
        echo "✓ Node.js $(node -v)"

  check-yarn:
    desc: Check Yarn is installed
    internal: true
    silent: true
    cmds:
      - |
        if ! command -v yarn > /dev/null 2>&1; then
          printf "Yarn is required; install? [Y/n] "
          read response
          response=${response:-Y}
          case "$response" in
            [Yy]*)
              echo "Installing Yarn via npm..."
              npm install -g yarn
              if [ $? -ne 0 ]; then
                echo "Failed to install Yarn. Please install manually: npm install -g yarn"
                exit 1
              fi
              ;;
            *)
              echo "Yarn is required to continue. Exiting."
              exit 1
              ;;
          esac
        fi
        echo "✓ Yarn $(yarn -v)"

  check-docker:
    desc: Check Docker is installed and running
    internal: true
    silent: true
    cmds:
      - |
        if ! command -v docker > /dev/null 2>&1; then
          printf "Docker is required; install? [Y/n] "
          read response
          response=${response:-Y}
          case "$response" in
            [Yy]*)
              OS_TYPE=$(uname -s)
              if [ "$OS_TYPE" = "Darwin" ]; then
                echo "Installing Docker via Homebrew..."
                brew install --cask docker
                echo "Please open Docker Desktop to complete setup, then run this task again."
                exit 1
              else
                echo "Please install Docker Desktop manually: https://www.docker.com/products/docker-desktop"
                exit 1
              fi
              ;;
            *)
              echo "Docker is required to continue. Exiting."
              exit 1
              ;;
          esac
        fi

        if ! docker info > /dev/null 2>&1; then
          echo "Docker is installed but not running. Please start Docker Desktop."
          exit 1
        fi
        echo "✓ Docker $(docker -v | cut -d' ' -f3 | tr -d ',')"

  check-infisical:
    desc: Check Infisical CLI is installed
    internal: true
    silent: true
    cmds:
      - |
        if ! command -v infisical > /dev/null 2>&1; then
          printf "Infisical CLI is required; install? [Y/n] "
          read response
          response=${response:-Y}
          case "$response" in
            [Yy]*)
              OS_TYPE=$(uname -s)
              if [ "$OS_TYPE" = "Darwin" ]; then
                echo "Installing Infisical CLI via Homebrew..."
                brew install infisical/get-cli/infisical
                if [ $? -ne 0 ]; then
                  echo "Failed to install Infisical CLI."
                  exit 1
                fi
              else
                echo "Please install Infisical CLI manually: https://infisical.com/docs/cli/overview"
                exit 1
              fi
              ;;
            *)
              echo "Infisical CLI is required to continue. Exiting."
              exit 1
              ;;
          esac
        fi
        echo "✓ Infisical CLI $(infisical --version 2>/dev/null | head -1)"

  check-stripe:
    desc: Check Stripe CLI is installed
    internal: true
    silent: true
    cmds:
      - |
        if ! command -v stripe > /dev/null 2>&1; then
          printf "Stripe CLI is required; install? [Y/n] "
          read response
          response=${response:-Y}
          case "$response" in
            [Yy]*)
              OS_TYPE=$(uname -s)
              if [ "$OS_TYPE" = "Darwin" ]; then
                echo "Installing Stripe CLI via Homebrew..."
                brew install stripe/stripe-cli/stripe
                if [ $? -ne 0 ]; then
                  echo "Failed to install Stripe CLI."
                  exit 1
                fi
              else
                echo "Please install Stripe CLI manually: https://stripe.com/docs/stripe-cli"
                exit 1
              fi
              ;;
            *)
              echo "Stripe CLI is required to continue. Exiting."
              exit 1
              ;;
          esac
        fi
        echo "✓ Stripe CLI $(stripe version 2>/dev/null)"

  check-infisical-auth:
    desc: Check user is authenticated to Infisical
    internal: true
    silent: true
    cmds:
      - |
        # Use 'infisical user get token' for fast auth check (doesn't try to fetch secrets)
        if ! infisical user get token > /dev/null 2>&1; then
          echo "You are not logged in to Infisical."
          printf "Run 'infisical login' now? [Y/n] "
          read response
          response=${response:-Y}
          case "$response" in
            [Yy]*)
              infisical login
              if [ $? -ne 0 ]; then
                echo "Failed to login to Infisical. Please try again."
                exit 1
              fi
              ;;
            *)
              echo "Infisical authentication is required to continue. Exiting."
              exit 1
              ;;
          esac
        fi
        echo "✓ Infisical authenticated"

  pull-secrets:
    desc: Pull secrets from Infisical and merge into .env.local
    internal: true
    silent: true
    deps:
      - check-infisical-auth
    cmds:
      - |
        echo "Pulling secrets from Infisical..."

        # Get secrets from Infisical in dotenv format
        TMP_SECRETS=$(mktemp)
        if ! infisical secrets --env=dev --path="{{.INFISICAL_PATH}}" --output=dotenv > "$TMP_SECRETS" 2>&1; then
          echo "Failed to fetch secrets from Infisical."
          rm -f "$TMP_SECRETS"
          exit 1
        fi

        INFISICAL_SECRETS=$(cat "$TMP_SECRETS")
        rm -f "$TMP_SECRETS"

        # Check if any secrets were returned
        if [ -z "$INFISICAL_SECRETS" ]; then
          echo "⚠ No secrets found in Infisical (dev environment). Skipping secret sync."
          echo "  Add secrets at: https://app.infisical.com"
          # Still copy .env.example as template if .env.local doesn't exist
          if [ ! -f .env.local ]; then
            cp .env.example .env.local
          fi
          exit 0
        fi

        # Start with .env.example as the template (preserves comments and structure)
        cp .env.example .env.local

        # Replace placeholder values with secrets from Infisical
        # .env.example uses KEY=\x7b\x7bKEY\x7d\x7d as placeholders (double braces)
        while IFS='=' read -r key value || [ -n "$key" ]; do
          # Skip empty lines
          [ -z "$key" ] && continue

          # Escape special characters in value for sed
          escaped_value=$(printf '%s' "$value" | sed 's/[&/\]/\\&/g')

          # Replace KEY=<any-value> with KEY=<secret-value>
          sed -i '' "s|^${key}=.*|${key}=${escaped_value}|g" .env.local
        done <<< "$INFISICAL_SECRETS"

        # Count secrets replaced
        SECRET_COUNT=$(echo "$INFISICAL_SECRETS" | grep -c "=" || echo "0")
        echo "✓ $SECRET_COUNT secrets applied to .env.local"

  start-supabase:
    desc: Start Supabase local development environment
    internal: true
    silent: true
    cmds:
      - |
        # Check if Supabase is already running by looking for the authentication keys
        if yarn db:status 2>&1 | grep -q "sb_publishable"; then
          echo "✓ Supabase is already running"
          exit 0
        fi

        echo "Starting Supabase..."
        yarn db:start

        # Verify it started successfully
        if ! yarn db:status 2>&1 | grep -q "sb_publishable"; then
          echo "Failed to start Supabase. Please check Docker is running."
          exit 1
        fi
        echo "✓ Supabase started"

  write-supabase-keys:
    desc: Extract Supabase keys and write to .env.local
    internal: true
    silent: true
    deps:
      - start-supabase
    cmds:
      - |
        echo "Extracting Supabase keys..."

        # Get the status output
        STATUS_OUTPUT=$(yarn db:status 2>&1)

        # Extract keys using the sb_publishable and sb_secret prefixes
        SUPABASE_URL=$(echo "$STATUS_OUTPUT" | grep -o 'http://[0-9.]*:54321' | head -1)
        PUBLISHABLE_KEY=$(echo "$STATUS_OUTPUT" | grep -o 'sb_publishable[^[:space:]│]*' | head -1)
        SECRET_KEY=$(echo "$STATUS_OUTPUT" | grep -o 'sb_secret[^[:space:]│]*' | head -1)

        if [ -z "$PUBLISHABLE_KEY" ] || [ -z "$SECRET_KEY" ]; then
          echo "Failed to extract Supabase keys. Is Supabase running?"
          exit 1
        fi

        # Default URL if not found
        SUPABASE_URL=${SUPABASE_URL:-"http://127.0.0.1:54321"}

        # Update .env.local with Supabase keys
        if [ ! -f .env.local ]; then
          echo ".env.local not found. Run 'task pull-secrets' first."
          exit 1
        fi

        # Replace the placeholder values with actual keys
        sed -i '' "s|^NEXT_PUBLIC_SUPABASE_URL=.*|NEXT_PUBLIC_SUPABASE_URL=${SUPABASE_URL}|" .env.local
        sed -i '' "s|^NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=.*|NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=${PUBLISHABLE_KEY}|" .env.local
        sed -i '' "s|^SUPABASE_SECRET_KEY=.*|SUPABASE_SECRET_KEY=${SECRET_KEY}|" .env.local

        echo "✓ Supabase keys written to .env.local"
        echo "  URL: $SUPABASE_URL"
        echo "  Publishable: ${PUBLISHABLE_KEY:0:20}..."
        echo "  Secret: ${SECRET_KEY:0:15}..."

  dev:webhooks:
    desc: Start Stripe webhook listener for local development
    silent: true
    cmds:
      - |
        # Verify .env.local exists
        if [ ! -f .env.local ]; then
          echo "Error: .env.local not found. Run 'task setup' first."
          exit 1
        fi

        # Extract STRIPE_SECRET_KEY from .env.local
        STRIPE_KEY=$(grep "^STRIPE_SECRET_KEY=" .env.local | cut -d '=' -f2)

        if [ -z "$STRIPE_KEY" ] || [ "$STRIPE_KEY" = '{{"{{"}}STRIPE_SECRET_KEY{{"}}"}}' ]; then
          echo "Error: STRIPE_SECRET_KEY not configured in .env.local"
          echo "Run 'task setup' to pull secrets from Infisical."
          exit 1
        fi

        echo "Configuring Stripe webhook listener..."

        # Get the webhook signing secret using --print-secret
        WEBHOOK_SECRET=$(stripe listen --api-key "$STRIPE_KEY" --print-secret 2>&1)

        if [ -z "$WEBHOOK_SECRET" ] || ! echo "$WEBHOOK_SECRET" | grep -q "^whsec_"; then
          echo "Error: Failed to get webhook signing secret from Stripe CLI"
          echo "Output: $WEBHOOK_SECRET"
          exit 1
        fi

        # Update STRIPE_WEBHOOK_SECRET in .env.local
        if grep -q "^STRIPE_WEBHOOK_SECRET=" .env.local; then
          sed -i '' "s|^STRIPE_WEBHOOK_SECRET=.*|STRIPE_WEBHOOK_SECRET=${WEBHOOK_SECRET}|" .env.local
        else
          echo "STRIPE_WEBHOOK_SECRET=${WEBHOOK_SECRET}" >> .env.local
        fi

        echo "✓ Webhook secret written to .env.local"
        echo "  Secret: ${WEBHOOK_SECRET:0:15}..."
        echo ""
        echo "Starting Stripe webhook listener..."
        echo "Forwarding to: http://localhost:3000/api/webhooks/complete-checkout"
        echo ""
        echo "Ready! Use 'stripe trigger checkout.session.completed' in another terminal to test."
        echo "Press Ctrl+C to stop."
        echo ""

        # Start the listener with forwarding
        stripe listen \
          --api-key "$STRIPE_KEY" \
          --forward-to "http://localhost:3000/api/webhooks/complete-checkout"
