# https://taskfile.dev

version: '3'

vars:
  NODE_VERSION_REQUIRED: "22"
  NODE_VERSION_EXACT: "22.21.1"

tasks:
  setup:
    desc: Set up local development environment
    silent: true
    cmds:
      - task: check-prereqs
      - echo ""
      - echo "✓ All prerequisites satisfied"
      - echo ""
      - echo "Proceeding with environment setup..."
      - task: pull-secrets

  check-prereqs:
    desc: Check that all required development prerequisites are installed
    silent: true
    cmds:
      - task: check-node
      - task: check-yarn
      - task: check-docker
      - task: check-infisical
      - task: check-stripe

  check-node:
    desc: Check Node.js is installed and meets version requirements
    internal: true
    silent: true
    cmds:
      - |
        if ! command -v node > /dev/null 2>&1; then
          printf "Node.js is required; install? [Y/n] "
          read response
          response=${response:-Y}
          case "$response" in
            [Yy]*)
              echo "Installing Node.js via nvm..."
              if command -v nvm > /dev/null 2>&1; then
                nvm install {{.NODE_VERSION_EXACT}}
                nvm use {{.NODE_VERSION_EXACT}}
              else
                echo "Please install Node.js v{{.NODE_VERSION_EXACT}} manually:"
                echo "  - Install nvm: https://github.com/nvm-sh/nvm"
                echo "  - Then run: nvm install {{.NODE_VERSION_EXACT}}"
                exit 1
              fi
              ;;
            *)
              echo "Node.js is required to continue. Exiting."
              exit 1
              ;;
          esac
        fi

        NODE_VERSION=$(node -v | sed 's/v//' | cut -d. -f1)
        if [ "$NODE_VERSION" -lt "{{.NODE_VERSION_REQUIRED}}" ]; then
          echo "Node.js v{{.NODE_VERSION_REQUIRED}}+ is required. Current version: $(node -v)"
          echo "Please upgrade Node.js to v{{.NODE_VERSION_EXACT}} (see .nvmrc)"
          exit 1
        fi
        echo "✓ Node.js $(node -v)"

  check-yarn:
    desc: Check Yarn is installed
    internal: true
    silent: true
    cmds:
      - |
        if ! command -v yarn > /dev/null 2>&1; then
          printf "Yarn is required; install? [Y/n] "
          read response
          response=${response:-Y}
          case "$response" in
            [Yy]*)
              echo "Installing Yarn via npm..."
              npm install -g yarn
              if [ $? -ne 0 ]; then
                echo "Failed to install Yarn. Please install manually: npm install -g yarn"
                exit 1
              fi
              ;;
            *)
              echo "Yarn is required to continue. Exiting."
              exit 1
              ;;
          esac
        fi
        echo "✓ Yarn $(yarn -v)"

  check-docker:
    desc: Check Docker is installed and running
    internal: true
    silent: true
    cmds:
      - |
        if ! command -v docker > /dev/null 2>&1; then
          printf "Docker is required; install? [Y/n] "
          read response
          response=${response:-Y}
          case "$response" in
            [Yy]*)
              OS_TYPE=$(uname -s)
              if [ "$OS_TYPE" = "Darwin" ]; then
                echo "Installing Docker via Homebrew..."
                brew install --cask docker
                echo "Please open Docker Desktop to complete setup, then run this task again."
                exit 1
              else
                echo "Please install Docker Desktop manually: https://www.docker.com/products/docker-desktop"
                exit 1
              fi
              ;;
            *)
              echo "Docker is required to continue. Exiting."
              exit 1
              ;;
          esac
        fi

        if ! docker info > /dev/null 2>&1; then
          echo "Docker is installed but not running. Please start Docker Desktop."
          exit 1
        fi
        echo "✓ Docker $(docker -v | cut -d' ' -f3 | tr -d ',')"

  check-infisical:
    desc: Check Infisical CLI is installed
    internal: true
    silent: true
    cmds:
      - |
        if ! command -v infisical > /dev/null 2>&1; then
          printf "Infisical CLI is required; install? [Y/n] "
          read response
          response=${response:-Y}
          case "$response" in
            [Yy]*)
              OS_TYPE=$(uname -s)
              if [ "$OS_TYPE" = "Darwin" ]; then
                echo "Installing Infisical CLI via Homebrew..."
                brew install infisical/get-cli/infisical
                if [ $? -ne 0 ]; then
                  echo "Failed to install Infisical CLI."
                  exit 1
                fi
              else
                echo "Please install Infisical CLI manually: https://infisical.com/docs/cli/overview"
                exit 1
              fi
              ;;
            *)
              echo "Infisical CLI is required to continue. Exiting."
              exit 1
              ;;
          esac
        fi
        echo "✓ Infisical CLI $(infisical --version 2>/dev/null | head -1)"

  check-stripe:
    desc: Check Stripe CLI is installed
    internal: true
    silent: true
    cmds:
      - |
        if ! command -v stripe > /dev/null 2>&1; then
          printf "Stripe CLI is required; install? [Y/n] "
          read response
          response=${response:-Y}
          case "$response" in
            [Yy]*)
              OS_TYPE=$(uname -s)
              if [ "$OS_TYPE" = "Darwin" ]; then
                echo "Installing Stripe CLI via Homebrew..."
                brew install stripe/stripe-cli/stripe
                if [ $? -ne 0 ]; then
                  echo "Failed to install Stripe CLI."
                  exit 1
                fi
              else
                echo "Please install Stripe CLI manually: https://stripe.com/docs/stripe-cli"
                exit 1
              fi
              ;;
            *)
              echo "Stripe CLI is required to continue. Exiting."
              exit 1
              ;;
          esac
        fi
        echo "✓ Stripe CLI $(stripe version 2>/dev/null)"

  check-infisical-auth:
    desc: Check user is authenticated to Infisical
    internal: true
    silent: true
    cmds:
      - |
        # Use 'infisical user get token' for fast auth check (doesn't try to fetch secrets)
        if ! infisical user get token > /dev/null 2>&1; then
          echo "You are not logged in to Infisical."
          printf "Run 'infisical login' now? [Y/n] "
          read response
          response=${response:-Y}
          case "$response" in
            [Yy]*)
              infisical login
              if [ $? -ne 0 ]; then
                echo "Failed to login to Infisical. Please try again."
                exit 1
              fi
              ;;
            *)
              echo "Infisical authentication is required to continue. Exiting."
              exit 1
              ;;
          esac
        fi
        echo "✓ Infisical authenticated"

  pull-secrets:
    desc: Pull secrets from Infisical and merge into .env.local
    internal: true
    silent: true
    deps:
      - check-infisical-auth
    cmds:
      - |
        echo "Pulling secrets from Infisical..."

        # Get secrets from Infisical in dotenv format
        # Store in temp file to properly check exit code
        TMP_SECRETS=$(mktemp)
        if ! infisical secrets --env=dev --output=dotenv > "$TMP_SECRETS" 2>&1; then
          echo "Failed to fetch secrets from Infisical."
          rm -f "$TMP_SECRETS"
          exit 1
        fi

        INFISICAL_SECRETS=$(cat "$TMP_SECRETS")
        rm -f "$TMP_SECRETS"

        # Check if any secrets were returned
        if [ -z "$INFISICAL_SECRETS" ]; then
          echo "⚠ No secrets found in Infisical (dev environment). Skipping secret sync."
          echo "  Add secrets at: https://app.infisical.com"
          touch .env.local
          exit 0
        fi

        # Create .env.local if it doesn't exist
        touch .env.local

        # Create a temporary file for the new .env.local
        TMP_ENV=$(mktemp)

        # Write Infisical secrets first
        echo "$INFISICAL_SECRETS" > "$TMP_ENV"

        # Append existing local-only values (keys not in Infisical secrets)
        # This preserves Supabase keys and other local-only settings
        while IFS= read -r line || [ -n "$line" ]; do
          # Skip empty lines and comments
          case "$line" in
            ""|\#*) continue ;;
          esac

          # Extract the key name
          KEY=$(echo "$line" | cut -d= -f1)

          # Check if this key exists in Infisical secrets
          if ! echo "$INFISICAL_SECRETS" | grep -q "^${KEY}="; then
            echo "$line" >> "$TMP_ENV"
          fi
        done < .env.local

        # Move temp file to .env.local
        mv "$TMP_ENV" .env.local

        # Count secrets written
        SECRET_COUNT=$(echo "$INFISICAL_SECRETS" | grep -c "=" || echo "0")
        echo "✓ $SECRET_COUNT secrets written to .env.local"
